UPDATE  dataelement set formname = '10.1.7 2.Are Heavy duty gloves available and correctly used?' WHERE uid = 'el8yox2y22J';
UPDATE  dataelement set formname = '11.1.3 5. From observation, was sufficient time given for the consultation?' WHERE uid = 'yyNnzfDmR3K';
UPDATE  dataelement set formname = '11.2.1 2. Are ANC guidelines, SOPs, checklist or job aids including wall charts available for reference?' WHERE uid = 'cRAJVCJvdmW';
UPDATE  dataelement set formname = '11.2.1 3. Is equipment available and functioning?' WHERE uid = 'udQna7WIpSC';
UPDATE  dataelement set formname = '11.2.3 2. Has any healthcare worker or provider(s) of immunization services received any training in child immunization services in the last two years?' WHERE uid = 'EbDF3Q2FxxA';
UPDATE  dataelement set formname = '11.2.3 4. Are the following vaccines available and usable on the day?(i. BCG ( ii. Polio ( iii. Measles and Rubella ( iv. Pentavalent ( v. Rotavirus (vi. Pneumococcal Vaccine (PCV 13) ( vii. Tetanus Toxoid ( viii. Human Papil' WHERE uid = 'JTHuvT1PR1L';
UPDATE  dataelement set formname = '11.3.1 1. Severe malaria treated according to standard treatment guidelines' WHERE uid = 'tQyyxIiwmhM';
UPDATE  dataelement set formname = '11.3.1 2.Severe pneumonia treated according to standard treatment guidelines' WHERE uid = 'ATjKVtsF0WD';
UPDATE  dataelement set formname = '12.3.1 1. Are there protocols for surgical procedures?' WHERE uid = 'z15emuMcQoV';
UPDATE  dataelement set formname = '12.3.2 1. Is there at least one cadre trained and certified to perform anaesthesia?' WHERE uid = 'SXG2MmvsGHV';
UPDATE  dataelement set formname = '12.3.3 1. Is there equipment to support safe surgical intervention appropriate to the level?' WHERE uid = 'fF5M7JbftZj';
UPDATE  dataelement set formname = '12.3.4 1. Is there constant power supply in the theatre?' WHERE uid = 'WwkLNmGfCm0';
UPDATE  dataelement set formname = '12.3.5 1. Check for the functionality of emergency equipment, Resuscitation And Airway Management System. i. Mayo Instrumentii. Diathermy Machin iii. Anaesthetic Trolley iv. Hoses v. Valves vi. Bellows Or Bag To Inflate Lungs' WHERE uid = 'RRtqpUgwPKn';
UPDATE  dataelement set formname = '12.3.6 1. Check for the washing and decontamination area for used equipment and linen' WHERE uid = 'qJVw73qqI3O';
UPDATE  dataelement set formname = '12.3.6 2. Check for the availability of sterilization facility for equipment and linen' WHERE uid = 'cM7RrPUohXd';
UPDATE  dataelement set formname = '12.3.6 3. Check for availability and condition of patient preparation area, changing room, scrubbing area, operating room and recovery room' WHERE uid = 'kDV1mTVkifN';
UPDATE  dataelement set formname = '12.3.6 4. Check if there is controlled access into the theatre' WHERE uid = 's2H8wRmmrD1';
UPDATE  dataelement set formname = '12.4.1 1 Are there SOPs and protocols for equipment?12.5.2 1 Are there SOPs and protocols for equipment?' WHERE uid = 'mi1poePnwBy';
UPDATE  dataelement set formname = '12.4.1 2. Is the radiology and imaging equipment functional?' WHERE uid = 'S2Fl1ZF2aIZ';
UPDATE  dataelement set formname = '12.4.1 3. and planned for preventive maintenance?' WHERE uid = 'iog6KfQLmZw';
UPDATE  dataelement set formname = '12.4.1.4 Is there a procedure for providing service after working hours?Check if there is an on call register with contact numbers for both x ray and ultrasound' WHERE uid = 'jUbpCgmw470';
UPDATE  dataelement set formname = '12.4.2 1 Are there suitably qualified staff?' WHERE uid = 'Rdvp97rKvgT';
UPDATE  dataelement set formname = '12.4.3 1 Is there equipment to support safe surgical intervention appropriate to the level?' WHERE uid = 'MkT0bt5LRCr';
UPDATE  dataelement set formname = '12.4.3 1. Is there a radiology safety program?' WHERE uid = 'lcwp2vluFwx';
UPDATE  dataelement set formname = '12.4.3 2. Is the radiology department complying with the radiology safety program?' WHERE uid = 'PDqur4lVu6z';
UPDATE  dataelement set formname = '12.4.3 3. Are the radiology staff using protective gear?' WHERE uid = 'q6vZ924ue7C';
UPDATE  dataelement set formname = '12.4.4 1 Is there constant power supply in the theatre?' WHERE uid = 'KzaQ49hTDh4';
UPDATE  dataelement set formname = '12.5.1 1.is formalin available ?' WHERE uid = 'sNCEhIjrOmy';
UPDATE  dataelement set formname = '12.5.1 2. Are there appropriate facilities for preserving dead bodies?' WHERE uid = 'R2K9elDaejI';
UPDATE  dataelement set formname = '12.5.1 3. Are appropriate PPE used when handling the body ?' WHERE uid = 'lDlazFpA9IC';
UPDATE  dataelement set formname = '12.6.1 1.Are there sufficient cleaning facilities?' WHERE uid = 'nutUI3zTFSY';
UPDATE  dataelement set formname = '12.6.1 2.Is food stored in a safe and clean environment?' WHERE uid = 'Iuzc9vPzWCF';
UPDATE  dataelement set formname = '12.6.1 3 Food handlers are free of contagious diseases' WHERE uid = 'GUPdALJKEXs';
UPDATE  dataelement set formname = '2.1.3 19.Is the AVAILABILITY of Social welfare officer at the duty station in accordance with the establishment [1]?' WHERE uid = 'VLpdyrZ6esx';
UPDATE  dataelement set formname = '2.1.5 2. Has the Health Facility Management Team been formally appointed, with Terms of Reference?' WHERE uid = 'qBJJFO4KQ08';
UPDATE  dataelement set formname = '2.1.5 4. Are Management Team meetings conducted at least monthly, and recorded?' WHERE uid = 'kdYUAYPsnMg';
UPDATE  dataelement set formname = '2.1.6 5. Have there been any documented quality improvement activities at the facility in the past six months?' WHERE uid = 'z0qR2MxNY7j';
UPDATE  dataelement set formname = '2.2.2 1. Check if the health facility has an operating bank account in the name of the facility' WHERE uid = 'ikvBVIP48GG';
UPDATE  dataelement set formname = '2.2.3 1. APPROPRIATE percentage expenditure on medicines and health products from statements of bank account and records for a six month period?' WHERE uid = 'Z6KMQ1WRXc4';
UPDATE  dataelement set formname = '2.3.2 1.Is there a suitable room for on-call staff within the facility?' WHERE uid = 'Fqf7TmZlBaP';
UPDATE  dataelement set formname = '3.1.2 4. Are the submitted HMIS data valid and reliable?' WHERE uid = 'TqmV1VeD8zi';
UPDATE  dataelement set formname = '3.2.2 1. Is the Facility Profile Report shared with the local administration?' WHERE uid = 'nMimRrvOUWB';
UPDATE  dataelement set formname = '4.1.3 1. Are individual job descriptions available for all staff and signed?' WHERE uid = 'AqwaxGtz5C9';
UPDATE  dataelement set formname = '5.1.3 1. Is there a charter on waiting times before a client is seen by healthcare provider for core services?' WHERE uid = 'YHjQ1TLbMPb';
UPDATE  dataelement set formname = '5.1.3 1. Is there a charter on waiting times before a client is seen by healthcare provider for core services?' WHERE uid = 'QozuX1R7DTH';
UPDATE  dataelement set formname = '5.1.5 1. Is information displayed on availability of the following resources (a) Plans and Budget? (b) Allocation of medicines & Supplies? (c) Revenue collection, received funds and expenditure?' WHERE uid = 'ZwKKCgCqKUM';
UPDATE  dataelement set formname = '6.2.1 3.Are facility staff aware of the emergency transport arrangements and procedures, including access to required contact numbers for transporter and referral facility?' WHERE uid = 'JxJlEWBr0lm';
UPDATE  dataelement set formname = '7.1.3 1. Methods in place' WHERE uid = 'w6sVFnWvvyl';
UPDATE  dataelement set formname = '7.1.3 2. Is the feedback mechanism in use?' WHERE uid = 'WVWhKTgEphl';
UPDATE  dataelement set formname = '7.1.3 3. Has there been any action on suggestions for improvement, or to address complaints from the feedback mechanism?' WHERE uid = 'MKEaSoqdk1U';
UPDATE  dataelement set formname = '7.1.3 4. Is there any community participation and engagement arising from the feedback mechanism?' WHERE uid = 'gdDxtmMjC1w';
UPDATE  dataelement set formname = '7.2.1 2. Is CLIENT 3 satisfied with their visit to the facility?' WHERE uid = 'HwaDguuitjx';
UPDATE  dataelement set formname = '9.2.1 4. Are the windows in good condition and screened?' WHERE uid = 'fWManKBw4ml';
UPDATE  dataelement set formname = '9.2.2 3. Are the facility ceilings in good condition?' WHERE uid = 'IvgSIbhCvbR';
