UPDATE section set sortorder=1 WHERE uid='gmBnpfTgcjC';
UPDATE section set sortorder=2 WHERE uid='VAKQGI47crV';
UPDATE section set sortorder=3 WHERE uid='bJo2Rir4xiP';
UPDATE section set sortorder=4 WHERE uid='uJttr5JVcok';
UPDATE section set sortorder=5 WHERE uid='MMMupo9ZjT6';
UPDATE section set sortorder=6 WHERE uid='S4DO2BYtmmE';
UPDATE section set sortorder=7 WHERE uid='B5tcYqE3xZR';
UPDATE section set sortorder=8 WHERE uid='vE22y8lwsDp';
UPDATE section set sortorder=9 WHERE uid='uXVIFDeJmNF';
UPDATE section set sortorder=10 WHERE uid='GH81G76vAY6';
UPDATE section set sortorder=11 WHERE uid='s3QdvkiXHGC';
UPDATE section set sortorder=12 WHERE uid='MF3yfmNaFS8';
UPDATE section set sortorder=13 WHERE uid='nncbexowqVL';
UPDATE section set sortorder=14 WHERE uid='kTFZcv4VUiy';
UPDATE section set sortorder= 1 WHERE uid='gj7TCAeLwZJ';
UPDATE section set sortorder= 2 WHERE uid='caSG8RWNGol';
UPDATE section set sortorder= 3 WHERE uid='Sgxi9cSGent';
UPDATE section set sortorder= 4 WHERE uid='hvb5MM7fXax';
UPDATE section set sortorder= 5 WHERE uid='oha2fsq4OXX';
UPDATE section set sortorder= 6 WHERE uid='pZtrEbh5Gp0';
UPDATE section set sortorder= 7 WHERE uid='EjWMLC0eMto';
UPDATE section set sortorder= 8 WHERE uid='iwRjNZfVkmX';
UPDATE section set sortorder= 9 WHERE uid='hXFgwYpa9kX';
UPDATE section set sortorder= 10 WHERE uid='eEdOKIXULHD';
UPDATE section set sortorder= 11 WHERE uid='Gii3WdlE5Tm';
UPDATE section set sortorder= 12 WHERE uid='DKjef2Yshxr';
UPDATE section set sortorder= 13 WHERE uid='UxP89FyvteU';
UPDATE section set sortorder= 14 WHERE uid='UCSDtveAun';
UPDATE section set sortorder=1 WHERE uid='yzKvJPPSnuw';
UPDATE section set sortorder=2 WHERE uid='ZD77v352kC2';
UPDATE section set sortorder=3 WHERE uid='OKXNG9YQYG1';
UPDATE section set sortorder=4 WHERE uid='We1h9aLrN5r';
UPDATE section set sortorder=5 WHERE uid='spVK0E73EAP';
UPDATE section set sortorder=6 WHERE uid='UP0oV7YaKLy';
UPDATE section set sortorder=7 WHERE uid='smSDHzM1WZ8';
UPDATE section set sortorder=8 WHERE uid='iHlvshTMpgg';
UPDATE section set sortorder=9 WHERE uid='wwkcagmhbwl';
UPDATE section set sortorder=10 WHERE uid='Mi9jNVCI01p';
UPDATE section set sortorder=11 WHERE uid='afncv1mmG7C';
UPDATE section set sortorder=12 WHERE uid='iFpfK9z3GMi';
UPDATE section set sortorder=13 WHERE uid='lPtKm7PNQf6';
UPDATE section set sortorder=14 WHERE uid='YyN1RAHIJ4l';
